#from : http://stackoverflow.com/questions/12328603/how-to-pass-command-line-argument-to-gnuplot
#also, same page:
#if (!exists("filename") instead of if ! exists("filename")
#You can input variables via switch -e
#$ gnuplot -e "filename='foo.data'" foo.plg
#In foo.plg you can then use that variable
#$ cat foo.plg 
#plot filename
#pause -1
#!/bin/bash
#1000: RAIN and TEMP
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/1000/RAIN/1000_RAIN.txt'" -e "title='Weather_Data_at_Station_1000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/1000/gnuplot/Rainfall_at_Station_1000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/1000/gnuplot/Rainfall_at_Station_1000.html'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/1000/TEMP/1000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#2000: RAIN and TEMP
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/2000/RAIN/2000_RAIN.txt'" -e "title='Weather_Data_at_Station_2000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/2000/gnuplot/Rainfall_at_Station_2000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/2000/gnuplot/Rainfall_at_Station_2000.html'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/2000/TEMP/2000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#3000: RAIN and TEMP
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/3000/RAIN/3000_RAIN.txt'" -e "title='Weather_Data_at_Station_3000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/3000/gnuplot/Rainfall_at_Station_3000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/3000/gnuplot/Rainfall_at_Station_3000.html'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/3000/TEMP/3000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#5000: RAIN and TEMP
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/5000/RAIN/5000_RAIN.txt'" -e "title='Weather_Data_at_Station_5000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/5000/gnuplot/Rainfall_at_Station_5000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/5000/gnuplot/Rainfall_at_Station_5000.html'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/5000/TEMP/5000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#7000: RAIN, DEPTH, TEMP
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/7000/RAIN/7000_RAIN.txt'" -e "title='Weather_Data_at_Station_7000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/7000/gnuplot/Rainfall_at_Station_7000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/7000/gnuplot/Rainfall_at_Station_7000.html'" -e "depth_name='/home/fbyne/workspace/instrument_processing/data/site/7000/DEPTH/7000_DEPTH.txt'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/7000/TEMP/7000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#8000: RAIN, DEPTH, TEMP
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/8000/RAIN/8000_RAIN.txt'" -e "title='Weather_Data_at_Station_8000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/8000/gnuplot/Rainfall_at_Station_8000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/8000/gnuplot/Rainfall_at_Station_8000.html'" -e "depth_name='/home/fbyne/workspace/instrument_processing/data/site/8000/DEPTH/8000_DEPTH.txt'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/8000/TEMP/8000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#9000: RAIN, DEPTH, TEMP
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/9000/RAIN/9000_RAIN.txt'" -e "title='Weather_Data_at_Station_9000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/9000/gnuplot/Rainfall_at_Station_9000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/9000/gnuplot/Rainfall_at_Station_9000.html'" -e "depth_name='/home/fbyne/workspace/instrument_processing/data/site/9000/DEPTH/9000_DEPTH.txt'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/9000/TEMP/9000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#10000: RAIN, TEMP_RTC
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/10000/RAIN/10000_RAIN.txt'" -e "title='Weather_Data_at_Station_10000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/10000/gnuplot/Rainfall_at_Station_10000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/10000/gnuplot/Rainfall_at_Station_10000.html'" -e "depth_name='/home/fbyne/workspace/instrument_processing/data/site/10000/DEPTH/10000_DEPTH.txt'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/10000/TEMP/10000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#11000: RAIN, TEMP_RTC
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/11000/RAIN/11000_RAIN.txt'" -e "title='Weather_Data_at_Station_11000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/11000/gnuplot/Rainfall_at_Station_11000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/11000/gnuplot/Rainfall_at_Station_11000.html'" -e "depth_name='/home/fbyne/workspace/instrument_processing/data/site/11000/DEPTH/11000_DEPTH.txt'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/11000/TEMP/11000_TEMP.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
#25000: RAIN, TEMP_RTC
gnuplot -e "rain_name='/home/fbyne/workspace/instrument_processing/data/site/25000/RAIN/25000_RAIN.txt'" -e "title='Weather_Data_at_Station_25000'" -e "filename='/home/fbyne/workspace/instrument_processing/data/site/25000/gnuplot/Rainfall_at_Station_25000.png'" -e "htmlfilename='/home/fbyne/workspace/instrument_processing/data/site/25000/gnuplot/Rainfall_at_Station_25000.html'" -e "temp_name='/home/fbyne/workspace/instrument_processing/data/site/25000/TEMP_RTC/25000_TEMP_RTC.txt'" /home/fbyne/workspace/instrument_processing/scripts/gnuplot/plot_rain_to_canvas_and_png.plt
